- hosts: laravel
  vars:
    username: 'iqbal'
    password: 'iqbal'
    domain: "lxc_php7_2.dev"
    domain: "lxc_php7_3.dev"
    domain: "lxc_php7_4.dev"
    domain: "lxc_php7_5.dev"
  roles:
    - php
    - lv
